file = open("Runtime.txt", encoding="utf-8")
m1 = (file.readline())
m2 = (file.readline())
m3 = (file.readline())
m4 = file.readline()
m5 = file.readline()
m6 = file.readline()
print(f'# {m1} {m2} {m3} {m4} {m5} {m6}')
print(m1,m2,m3,m4,m5,m6, sep=" ", end =" ")